import "./globals.css";
import NavBar from "./components/navbar";
import { CartProvider } from "context/cartContext";
import ShoppingCartModal from "./components/shoppingCartModal";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <NavBar />
          <ShoppingCartModal />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
